const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(path.join(__dirname, '..', 'LOOOVE-demo.html'), 'utf8');
const pagesEntrypointPath = path.join(__dirname, '..', '..', 'LOOOVE-demo.html');
assert.equal(fs.readFileSync(pagesEntrypointPath, 'utf8'), html, 'GitHub Pages 根入口应与新demo的最新版 HTML 完全一致');
for (const asset of ['背景图.png', '硬件图.png', '1.png', '呼吸画线.jpg', path.join('抽卡', '背面.png'), path.join('抽卡', '28.png'), path.join('抽卡', '31.png'), path.join('抽卡', '36.png')]) {
  assert.equal(fs.existsSync(path.join(__dirname, '..', '..', asset)), true, `GitHub Pages 根目录应包含新 Demo 素材：${asset}`);
}
assert.equal(
  fs.readFileSync(path.join(__dirname, '..', '..', '硬件图.png')).equals(fs.readFileSync(path.join(__dirname, '..', '硬件图.png'))),
  true,
  '仓库根入口与新demo应使用同一张当前硬件图'
);

const activeMarkup = html.replace(/<!--[\s\S]*?-->/g, '');
assert.doesNotMatch(activeMarkup, /<aside\b|class="brand"|class="principles"|class="hw-showcase"/, '手机外部的品牌文案与硬件展示应从页面结构中移除');
assert.match(activeMarkup, /<div class="stage">\s*<div class="center-col">\s*<div class="phone-wrap">\s*<div class="phone" id="phone">/, '舞台区域应只保留居中的手机屏幕');
assert.match(html, /\.stage\{display:flex;align-items:center;justify-content:center;min-height:100vh;[^}]*z-index:1\}/, '单手机舞台应在页面中水平垂直居中');
assert.match(html, /function fitPhone\(\)[\s\S]*?window\.innerWidth\*\.92\)\/390/, '手机缩放应按真实宽度计算，避免窄屏显示过小');

assert.match(html, /<div class="mine-profile-top">[\s\S]*?Candice[\s\S]*?<button class="mine-profile-entry" onclick="openOverlay\('ov-xiaoha'\)"[^>]*>[\s\S]*?<b>个人档案<\/b>[\s\S]*?<small>查看个性化画像<\/small>[\s\S]*?<\/button>\s*<div class="mine-actions">/, '我的页应在 Candice 与三项测量之间新增独立的个人档案入口');
assert.match(html, /\.mine-profile-entry\{display:grid;grid-template-columns:34px 1fr 18px;[^}]*width:100%;[^}]*border-radius:16px/, '个人档案入口应使用独立整行卡片布局');
assert.match(html, /\.mine-profile-entry,\.mine-act-btn\{background:rgba\(255,252,248,\.62\);backdrop-filter:blur\(16px\) saturate\(160%\);-webkit-backdrop-filter:blur\(16px\) saturate\(160%\);border:1px solid rgba\(255,255,255,\.82\);box-shadow:0 2px 10px rgba\(0,0,0,\.05\),inset 0 1px 0 rgba\(255,255,255,\.88\)\}/, '个人档案应与三项测量共用同一套底色、毛玻璃、边框和阴影');
assert.match(html, /id="ov-xiaoha"[\s\S]*?class="sr-toptitle">个人档案<\/div>[\s\S]*?class="xh-name">Candice，32 岁<\/div>/, '个人档案入口应复用原 Candice 画像子页面并更新页面标题');
assert.match(html, /class="mine-ring-wrap" id="devRingIcon">\s*<img src="\.\/硬件图\.png" alt="LOOOVE 智能戒指实物图">\s*<\/div>/, '我的设备卡应使用当前硬件图替代线性戒指图标');
assert.doesNotMatch((html.match(/class="mine-ring-wrap" id="devRingIcon">([\s\S]*?)<\/div>/) || [])[1] || '', /<svg\b/, '我的设备卡不应继续显示旧 SVG 图标');
assert.match(html, /\.mine-ring-wrap img\{width:46px;height:46px;object-fit:contain;[^}]*opacity:\.82\}/, '戒指实物图应在设备圆形容器内完整显示');
assert.match(html, /\.mine-ring-wrap\.live img\{opacity:1;animation:ringPulse/, '戒指实物图应继续响应连接状态');
assert.doesNotMatch(html, /基于生理和情绪信号的AI身心成长教练/, '旧品牌介绍应移除');
assert.equal(fs.existsSync(path.join(__dirname, '..', '背景图.png')), true, '本地背景图片文件应存在');
assert.match(html, /url\(['"]\.\/背景图\.png['"]\)/, '首页应使用本地背景图.png');
assert.match(html, /url\(['"]\.\/背景图\.png['"]\) center 42%\/cover no-repeat/, '首页背景图取景应向上移动');
assert.match(html, /\.app\.home-visual::before\{opacity:calc\(var\(--homeVisual\) \* \.64\)\}/, '首页背景图透明度应为原来的 0.64 倍（当前值的 0.8 倍）');
assert.equal((html.match(/class="home-awareness-card"/g) || []).length, 2, '早晚首页都应展示实时身心觉察卡');
assert.match(html, /\.home-scroll-area\{[^}]*overflow-y:hidden[^}]*overscroll-behavior:none[^}]*touch-action:none/, '首页觉察内容应固定并禁止纵向滚动');
assert.doesNotMatch(html.replace(/<!--[\s\S]*?-->/g, ''), /id="flowPicker"/, '页面外部的实时身心觉察/日常切换应移除');
assert.doesNotMatch(html.replace(/<!--[\s\S]*?-->/g, ''), /home-awareness-kicker/, '首页不应再展示实时身心觉察顶部文案');
assert.match(html, /class="home-awareness-title"[^>]*onclick="openBodyAwareness\(2\)"[^>]*>渐入平衡<\/button>/, '状态词应可进入指定觉察详情');
assert.match(html, /class="home-awareness-score"[^>]*onclick="openAwarenessBodyState\(\)"[^>]*>[\s\S]*?Loooveness 56/, '分值按钮应可进入身体状态页');
assert.equal((html.match(/class="home-consultant-label">LOOOVE<\/div>/g) || []).length, 2, '早晚首页的觉察卡标题应统一显示 LOOOVE');
assert.match(html, /\.home-awareness-title\{[^}]*color:#5a5a5a/, '首页状态词应使用参考图的中性灰配色');
assert.match(html, /\.home-awareness-score\{[^}]*border:1px solid rgba\(76,68,64,\.12\)[^}]*background:#fff[^}]*color:var\(--primary\)[^}]*box-shadow:0 6px 18px rgba\(79,68,63,\.14\),inset 0 1px 0 rgba\(255,255,255,\.96\)/, 'Loooveness 白色按钮应使用中性细描边和柔和悬浮阴影增强辨识度');
assert.doesNotMatch(html, /\.home-awareness-score\{[^}]*backdrop-filter/, 'Loooveness 分值按钮不应再使用毛玻璃模糊');
assert.match(html, /\.home-awareness-score\{[^}]*font-size:11\.5px;font-weight:600;letter-spacing:\.12em/, 'Loooveness 英文和数字应使用 600 字重与精致字距');
assert.match(html, /\.home-awareness-score:hover\{[^}]*background:#fff[^}]*color:#ee6f55/, 'Loooveness 分值按钮悬停时应保持白底并加深文字橙色');
assert.match(html, /\.home-consultant\{[^}]*display:flex[^}]*flex-direction:column[^}]*background:rgba\(255,255,255,\.30\)[^}]*backdrop-filter:blur\(22px\)/, 'Consultant 文案毛玻璃应进一步透明');
assert.match(html, /\.home-consultant\{margin-top:100px/, 'Consultant 毛玻璃卡应继续下移并固定');
assert.match(html, /\.home-consultant-label\{[^}]*display:flex[^}]*align-items:center[^}]*gap:8px/, 'Consultant 标题应为绿色状态点预留布局');
assert.match(html, /\.home-consultant-label::before\{[^}]*background:#62b887/, 'Consultant 标题前应显示绿色状态点');
assert.match(html, /\.home-consultant-copy\{[^}]*font-size:clamp\(15px,4\.1vw,17px\)/, '身心觉察正文应放大');
assert.equal((html.match(/class="home-consultant-next"[^>]*onclick="openHomeAwarenessPlaceholder\(\)"/g) || []).length, 2, '早晚首页都应提供 Consultant Agent 跳转按钮');
assert.match(html, /\.home-consultant-next\{align-self:center;width:72%;[^}]*justify-content:center;gap:0/, 'Consultant Agent 按钮文字应居中对齐');
assert.match(html, /\.home-consultant-next\{[^}]*font-size:13px;font-weight:600;letter-spacing:\.08em/, 'Consultant Agent 英文字重应由 400 提升至 600，并使用更精致的字距');
assert.match(html, /\.home-consultant-next\{[^}]*border:1px solid rgba\(76,68,64,\.12\)[^}]*background:#fff;color:var\(--primary\)[^}]*box-shadow:0 6px 18px rgba\(79,68,63,\.14\),inset 0 1px 0 rgba\(255,255,255,\.96\)/, 'Consultant Agent 白色按钮应使用中性细描边和柔和悬浮阴影增强辨识度');
assert.doesNotMatch(html, /\.home-consultant-next\{[^}]*backdrop-filter/, 'Consultant Agent 按钮不应再使用毛玻璃模糊');
assert.match(html, /\.home-consultant-next:hover\{[^}]*background:#fff[^}]*color:#ee6f55/, 'Consultant Agent 按钮悬停时应保持白底并加深文字橙色');
assert.match(html, /\.home-consultant\{margin-top:100px;width:100%;padding:18px 18px 24px;/, '互动按钮与毛玻璃卡片底边之间应保留更舒展的留白');
assert.equal((html.match(/<button class="home-consultant-next"[^>]*>[\s\S]*?<span>互动<\/span>\s*<\/button>/g) || []).length, 2, '早晚首页按钮都应显示“互动”');
assert.doesNotMatch(html, /<span>互动<\/span>\s*<svg/, '互动按钮不应显示箭头');
assert.match(html, /id="homeAwarenessPlaceholder"/, '应保留一个可跳转的空白新页面');
assert.match(html, /id="homeAwarenessPlaceholder"[\s\S]*?<div class="sr-toptitle">互动<\/div>/, '跳转后的页面标题应为“互动”');
assert.match(html, /id="homeAwarenessPlaceholder"[\s\S]*?<button class="consultant-search-btn" type="button" aria-label="搜索互动记录">[\s\S]*?<circle cx="10\.5" cy="10\.5" r="5\.5"[\s\S]*?<path d="M14\.5 14\.5L19 19"/, '互动页标题栏右上角应提供线性搜索图标');
assert.match(html, /\.consultant-search-btn\{width:28px;height:36px;[^}]*border:0[^}]*background:transparent[^}]*color:var\(--consultant-ink\)/, '搜索按钮应无白色底框并与返回按钮保持同等点击尺寸');
const consultantPageMarkup = (html.match(/<div class="home-child-screen" id="homeAwarenessPlaceholder">([\s\S]*?)(?=<div class="home-state-screen" id="homeBodyState">)/) || [])[1] || '';
assert.match(html, /id="consultantAgentFeed"/, '互动页应提供可滚动的顾问消息时间线');
assert.match(html, /#homeAwarenessPlaceholder \.sr-topbar\{height:62px;background:transparent;\s*border-bottom:0/, '互动页标题栏应去掉白色框层');
assert.match(html, /\.home-awareness-placeholder-body\.consultant-agent-body\{inset:120px 0 0;overflow:hidden\}/, '互动内容应从标题栏下方开始，滚动时不得与标题重叠');
assert.doesNotMatch(consultantPageMarkup, /今天 · 07:30|consultant-thread-time/, '互动页不应再显示冗余的日期时间分隔');
assert.match(consultantPageMarkup, /今晨恢复偏慢，适合从容启动。/, '早报顶部应使用一句简短结论');
assert.match(html, /\.consultant-report-title\{[^}]*white-space:nowrap/, '早报顶部结论不得换行');
assert.doesNotMatch(consultantPageMarkup, /今天适合慢一点进入状态|恢复正在发生，但身体还没有完全跟上你的计划。|consultant-report-sub/, '早报不应继续显示旧的两句文案');
assert.doesNotMatch(consultantPageMarkup, /consultant-readiness-ring/, 'Loooveness 分值不应再使用圆环');
assert.match(html, /\.consultant-primary-metrics\{display:grid;grid-template-columns:repeat\(2,1fr\)/, 'Loooveness 与睡眠应排列在第一行');
assert.match(html, /\.consultant-secondary-metrics\{display:grid;grid-template-columns:repeat\(3,1fr\)/, 'HRV、静息心率与压力应排列在第二行');
assert.match(consultantPageMarkup, /consultant-primary-metrics[\s\S]*?Loooveness[\s\S]*?56[\s\S]*?睡眠[\s\S]*?6小时42分/, '首行应只展示 Loooveness 与睡眠');
assert.match(consultantPageMarkup, /consultant-secondary-metrics[\s\S]*?HRV[\s\S]*?32[\s\S]*?静息心率[\s\S]*?70[\s\S]*?压力[\s\S]*?3\.3/, '第二行应展示三项身体数据');
assert.match(html, /\.consultant-primary-value\{[^}]*font-size:22px/, '首行核心数据字号应明显放大');
assert.match(html, /\.consultant-secondary-value\{[^}]*font-size:16px/, '第二行数据字号应提升可读性');
assert.match(html, /#homeAwarenessPlaceholder\{[^}]*--consultant-ink:#5f5f5f;--consultant-muted:#9a918d;--consultant-accent:var\(--primary\)/, '互动页应将文字颜色收敛为主灰、次灰和首页橙三种');
assert.match(html, /\.consultant-dispatch-card,\.consultant-analysis-card\{[^}]*background:rgba\(255,255,255,\.68\)[^}]*backdrop-filter:blur\(22px\)[^}]*box-shadow:0 14px 34px rgba\(110,88,78,\.11\)/, '早报与 Agent 解读应使用同一块清晰可辨的柔白毛玻璃表面');
assert.match(html, /\.consultant-user-bubble\{[^}]*background:rgba\(255,127,99,\.12\)[^}]*color:var\(--consultant-accent\)[^}]*box-shadow:0 10px 24px rgba\(139,91,75,\.10\)/, '用户消息应使用浅橙独立气泡，与 Agent 内容形成清晰层级');
assert.match(html, /\.consultant-primary-metric\{[^}]*background:transparent/, '核心数据不应再使用独立灰底小卡片');
assert.match(html, /\.consultant-report-title\{font-family:var\(--serif\)/, '互动页标题应继承首页的衬线字体');
assert.match(html, /早间报告[\s\S]*?睡眠[\s\S]*?6小时42分[\s\S]*?HRV[\s\S]*?32[\s\S]*?静息心率[\s\S]*?70[\s\S]*?压力[\s\S]*?3\.3/, '早间报告应展示睡眠、HRV、静息心率和压力仪表盘');
assert.match(consultantPageMarkup, /昨夜恢复低于近期水平。上午先做熟悉的事，把需要判断的任务留到状态打开之后。/, '早报解读应简短并给出清晰行动建议');
assert.match(html, /class="consultant-user-bubble">我最近压力好大<\/div>/, '互动页应展示用户发给顾问的压力消息');
assert.match(consultantPageMarkup, /最近的录音中，你们围绕需求排期与实现边界产生了争辩；过程中，你的语速明显加快，语气里也流露出被压抑的愤怒。/, '声音线索应完整描述会议争辩与被压抑的愤怒');
assert.match(consultantPageMarkup, /会议后紧张感持续，HRV 低于个人基线，情绪压力保持在高位。/, '身体数据应说明紧张、低 HRV 与高情绪压力');
assert.match(consultantPageMarkup, /你在会议中提出需求后，被开发直接反驳，双方争辩了几句。虽然会议已经结束，但那股被顶回来的恼火，还是继续留在身体里。/, '推测应具体描述会议结束后仍残留的恼火');
assert.doesNotMatch(consultantPageMarkup, /一种可能 · 推测，不是事实/, '推测标题应精简为“推测”');
assert.doesNotMatch(consultantPageMarkup, /这个判断接近吗|consultant-hypothesis-check|consultant-hypothesis-actions/, '互动页应移除判断确认文案与校准选项');
assert.doesNotMatch(consultantPageMarkup, /主动发送|联合解读|已授权的最近3段戒指录音|consultant-proactive-tag|consultant-source-row|consultant-report-trend/, '互动页应移除状态标签、录音开场句、来源胶囊与折线图');
assert.equal((consultantPageMarkup.match(/<b>LOOOVE<\/b>/g) || []).length, 7, '互动页七条 Agent 消息都应显示 LOOOVE');
assert.match(consultantPageMarkup, /LOOOVE 在线 · 戒指数据已同步/, '互动页在线状态应使用 LOOOVE 品牌名');
const consultantDayMarkers = [...consultantPageMarkup.matchAll(/class="consultant-day-marker"><span>([^<]+)<\/span>/g)].map(([, label]) => label);
assert.deepEqual(consultantDayMarkers, ['6月11日 · 星期四', '6月12日 · 星期五'], '互动流应按连续两天分组显示日期');
assert.match(consultantPageMarkup, /6月11日 · 星期四[\s\S]*?<time>07:30<\/time>[\s\S]*?我最近压力好大[\s\S]*?<time>10:19<\/time>[\s\S]*?<time>23:47<\/time>[\s\S]*?6月12日 · 星期五[\s\S]*?我有点烦躁[\s\S]*?<time>14:09<\/time>[\s\S]*?class="consultant-agent-message consultant-taste-message"[\s\S]*?<time>16:40<\/time>[\s\S]*?我最近有点迷茫[\s\S]*?<time>21:17<\/time>/, '早报、压力对话与音乐属于第一天，味觉探索应位于第二天的烦躁互动与抽卡互动之间');
assert.match(html, /\.consultant-day-marker\{display:flex;justify-content:center;[^}]*\}/, '日期应使用居中的轻量标记，不增加横向分割线');
assert.match(html, /\.consultant-evidence-item\{[^}]*background:transparent[^}]*border-top:1px solid rgba\(95,95,95,\.10\)/, '联合解读应使用统一的无底色分隔样式');
assert.match(html, /\.consultant-hypothesis\{[^}]*background:transparent[^}]*border-left:0[^}]*border-top:1px solid rgba\(95,95,95,\.10\)/, '事件推测应取消彩色嵌套卡片并统一分隔样式');
assert.equal((consultantPageMarkup.match(/consultant-section-label/g) || []).length, 12, '三组声音、身体、推测与推荐模块应共用同一个标题类');
assert.match(html, /\.consultant-section-label\{color:var\(--consultant-accent\);font-family:var\(--sans\);font-size:11px;font-weight:700;letter-spacing:\.08em\}/, '四个模块标题应使用完全一致的字色、字体、字号和字重');
assert.match(html, /\.consultant-evidence-item\{display:block;/, '声音与身体模块应改为上下结构');
assert.match(html, /\.consultant-evidence-item span\{display:block;margin-top:7px;/, '声音与身体文案应在标题下方另起一行并自然换行');
assert.match(consultantPageMarkup, /<div class="consultant-intervention-title consultant-section-label">推荐<\/div>/, '干预分区标题应简化为“推荐”');
assert.doesNotMatch(consultantPageMarkup, /把争辩留在会议里/, '推荐区不应继续使用旧标题');
assert.match(consultantPageMarkup, /class="consultant-mantra-card"[\s\S]*?今日心法[\s\S]*?<p>方案被反对，不等于能力被否定。<\/p>\s*<footer>带走有用的信息，允许自己有情绪；<br>等愤怒过去，再决定什么值得回应。<\/footer>/, '心法应使用精简的一行主句与小字解释');
assert.doesNotMatch(consultantPageMarkup, /分歧可以讨论|轻视不用接住|把对方的情绪留给对方/, '推荐区不应残留旧心法');
assert.doesNotMatch(consultantPageMarkup, /consultant-care-action|launchConsultantIntervention|conflict-reset|复述|对着戒指说三句话|90 秒降载|2 分钟复位/, '心法推荐不应再包装成需要用户执行的任务');
assert.match(html, /\.consultant-mantra-card\{[^}]*padding:18px 17px 17px[^}]*background:linear-gradient\(145deg,rgba\(255,255,255,\.84\),rgba\(255,244,239,\.68\)\)[^}]*box-shadow:0 12px 30px rgba\(139,91,75,\.10\)/, '心法卡应使用与页面一致的暖白层次和克制阴影');
assert.match(html, /\.consultant-mantra-card p\{[^}]*white-space:nowrap/, '心法主句应保持一行显示');
assert.match(html, /\.consultant-evidence-item span,\.consultant-hypothesis p,\.consultant-report-insight,\.consultant-proactive-copy,\.consultant-mantra-card footer,\.consultant-inline-agent\{[^}]*color:var\(--consultant-ink\)[^}]*font-family:var\(--sans\)[^}]*font-size:13px[^}]*font-weight:400[^}]*line-height:1\.7/, '声音线索、身体数据、推测、早报总结、深夜说明、心法解释与主动回复应共用正文样式');
assert.match(html, /\.consultant-mantra-card footer\{[^}]*padding-top:0[^}]*border-top:0/, '心法主句与解释之间不应显示分割线');
assert.doesNotMatch(consultantPageMarkup, /基于昨夜戒指数据/, '互动页早间报告不应显示“基于昨夜戒指数据”');
assert.match(html, /\.consultant-report-title,\.consultant-mantra-card p,\.consultant-proactive-title,\.consultant-sleep-music-name,\.consultant-breath-line-title,\.consultant-breath-feedback-card h3,\.consultant-taste-recommendation h3,\.consultant-card-draw-title\{color:var\(--consultant-ink\);font-family:var\(--serif\);font-size:14px;font-weight:600;line-height:1\.45;letter-spacing:0\}/, '互动页八处核心标题应统一使用早间报告标题的字体、颜色、字号与字重');
assert.match(consultantPageMarkup, /class="consultant-agent-message consultant-proactive-message"[\s\S]*?<time>23:47<\/time>[\s\S]*?身体还没有进入休息。[\s\S]*?已经很晚了，你还没有入睡，Loooveness 降至 41。我为你生成了一段音乐，陪你度过这段仍然清醒的时间。/, '深夜主动消息应使用更新后的时间与陪伴式助眠文案');
assert.match(consultantPageMarkup, /专属助眠音乐[\s\S]*?慢慢落下来/, '主动干预应保留专属助眠音乐的类型与名称');
assert.match(consultantPageMarkup, /id="consultantSleepMusicButton"[^>]*onclick="toggleConsultantSleepMusic\(this\)"[^>]*aria-pressed="false"/, '专属助眠音乐应提供可交互的播放按钮');
const sleepMusicButtonMarkup = (consultantPageMarkup.match(/<button class="consultant-sleep-music-button"[\s\S]*?<\/button>/) || [])[0] || '';
assert.doesNotMatch(sleepMusicButtonMarkup, /12:00|consultant-sleep-state|>播放<|consultant-sleep-music-meta|根据此刻心率、HRV 与呼吸节律生成/, '音乐卡片不应显示时长、播放文字或底部说明小字');
assert.match(html, /\.consultant-proactive-card\{[^}]*background:linear-gradient\(145deg,rgba\(255,250,247,\.92\),rgba\(247,232,225,\.72\)\)[^}]*box-shadow:0 16px 38px rgba\(110,88,78,\.13\)/, '主动关心卡应以更温暖但统一的表面层与普通解读区分');
assert.match(html, /\.consultant-sleep-music-button\.playing \.consultant-sleep-wave i\{animation:consultantSleepWave/, '播放后音乐波形应提供清晰的动态反馈');
assert.match(html, /\.consultant-sleep-music-label,\.consultant-sleep-music-name\{display:block\}/, '音乐卡片应只保留类型与曲名两行');
assert.match(html, /function toggleConsultantSleepMusic\(button\)[\s\S]*?aria-pressed[\s\S]*?classList\.toggle\('playing',isPlaying\)/, '助眠音乐按钮应仅通过播放图标与波形切换状态');
assert.equal(fs.existsSync(path.join(__dirname, '..', '呼吸画线.jpg')), true, '呼吸画线本地图片应存在');
assert.match(consultantPageMarkup, /class="consultant-user-bubble">我有点烦躁<\/div>/, '音乐与抽卡之间应新增用户的烦躁消息');
assert.match(consultantPageMarkup, /class="consultant-agent-message consultant-restless-message"[\s\S]*?<time>14:09<\/time>[\s\S]*?<b class="consultant-section-label">声音线索<\/b><span>最近的录音里没有出现明显冲突或反复提及的困扰，语速、语气都接近平时。<\/span>[\s\S]*?<b class="consultant-section-label">身体数据<\/b><span>HRV 39ms、静息心率 68bpm，压力曲线处在个人正常范围，身体没有明显负荷升高。<\/span>/, '烦躁解读应说明近期无明显事件且身体信号平稳');
assert.match(consultantPageMarkup, /consultant-restless-message[\s\S]*?consultant-hypothesis-label consultant-section-label">推测<\/div>\s*<p>这次烦躁更像是注意力积累了一点噪音，不一定对应某件具体的事。<\/p>[\s\S]*?consultant-intervention-title consultant-section-label">推荐<\/div>/, '烦躁解读应给出克制推测并只推荐一个互动');
assert.match(consultantPageMarkup, /class="consultant-breath-line-preview" onclick="openMindDrawing\('consultant'\)"[^>]*>[\s\S]*?<img src="\.\/呼吸画线\.jpg" alt="跟着呼吸画线">[\s\S]*?class="consultant-breath-line-label" id="consultantBreathLineLabel">绘画疗愈<\/span>[\s\S]*?class="consultant-breath-line-title">跟着呼吸画线<\/span>/, '烦躁推荐应使用本地图片并将类型改为绘画疗愈');
const breathLineButtonMarkup = (consultantPageMarkup.match(/<button class="consultant-breath-line-preview"[\s\S]*?<\/button>/) || [])[0] || '';
assert.doesNotMatch(breathLineButtonMarkup, /轻量表达|consultant-breath-line-meta|吸气向上，呼气向下，连续画三轮/, '呼吸画线卡片不应保留底部说明小字');
assert.match(html, /\.consultant-breath-line-preview\{width:100%;margin-top:10px;padding:10px;border:0;border-radius:20px;display:grid;grid-template-columns:58px 1fr;/, '呼吸画线入口应使用与互动页一致的双栏柔白卡片');
assert.match(html, /function openMindDrawing\(origin='mind'\)[\s\S]*?mindDrawingOrigin=origin/, '绘画页应记录从互动页或情绪页进入的来源');
assert.match(html, /function finishMindDrawing\(\)[\s\S]*?mindDrawingOrigin==='consultant'[\s\S]*?consultantBreathLineLabel[\s\S]*?绘画疗愈 · 已完成/, '从互动页完成呼吸画线后应在类型标签中更新完成状态');
assert.match(consultantPageMarkup, /class="consultant-user-row consultant-drawing-user"[\s\S]*?<div class="consultant-user-name">我 · 14:15<\/div>[\s\S]*?<figure class="consultant-drawing-bubble">[\s\S]*?<img src="\.\/呼吸画线\.jpg" alt="我完成的呼吸画线作品">[\s\S]*?<figcaption>呼吸画线 · 已完成<\/figcaption>/, '绘画任务下方应模拟展示用户完成并发送的呼吸画线作品');
assert.match(consultantPageMarkup, /class="consultant-agent-message consultant-breath-feedback-message"[\s\S]*?<time>14:16<\/time>[\s\S]*?class="consultant-breath-feedback-kicker">反馈<\/div>[\s\S]*?<h3>身体开始松开了。<\/h3>/, '用户发送作品后，LOOOVE 应使用简洁的“反馈”标题说明即时身体变化');
assert.doesNotMatch(consultantPageMarkup, /调息反馈/, '互动页不应继续显示“调息反馈”旧标题');
assert.match(html, /\.consultant-agent-feed \.consultant-keyword\{display:inline;margin:0;color:var\(--consultant-accent\);font-weight:400;font-style:normal\}/, '互动关键词必须保持行内布局，只改变颜色且不加粗');
const consultantKeywordSource = (html.match(/const CONSULTANT_KEYWORDS=\[([\s\S]*?)\];/) || [])[1] || '';
for (const keyword of ['语速明显加快','被压抑的愤怒','HRV 低于个人基线','情绪压力保持在高位','Loooveness 降至 41','HRV 39ms','静息心率 68bpm','68','64 bpm','43 ms']) {
  assert.ok(consultantKeywordSource.includes(`'${keyword}'`), `互动关键词表应包含：${keyword}`);
}
assert.match(html, /function highlightConsultantKeywords\(root=document\.getElementById\('consultantAgentFeed'\)\)[\s\S]*?NodeFilter\.SHOW_TEXT[\s\S]*?className='consultant-keyword'/, '互动页应在保留原文结构的前提下为关键词添加橙色高亮');
assert.match(html, /highlightConsultantKeywords\(\);/, '页面初始化时应执行互动关键词高亮');
assert.match(html, /\.consultant-drawing-bubble\{[^}]*background:rgba\(255,255,255,\.9\)[^}]*box-shadow:0 12px 28px rgba\(110,88,78,\.12\)/, '用户画作应使用清晰但克制的独立图片气泡');
assert.match(html, /\.consultant-breath-feedback-card\{[^}]*background:rgba\(255,255,255,\.72\)[^}]*box-shadow:0 14px 34px rgba\(110,88,78,\.11\)/, '调息反馈应沿用互动页现有的柔白内容表面');
assert.match(consultantPageMarkup, /class="consultant-agent-message consultant-taste-message"[\s\S]*?<time>16:40<\/time>[\s\S]*?class="consultant-taste-signal">刚才的声音与身体数据都没有明显异常，但体表温度已连续 40 分钟高于个人午后基线 0\.4°C。此刻的烦躁更像轻微燥热与感官疲劳。<\/p>[\s\S]*?class="consultant-taste-practice"[\s\S]*?class="consultant-taste-kicker">探索尝试<\/div>/, 'LOOOVE 应先说明触发信号，再把探索尝试作为下方干预标题');
assert.match(consultantPageMarkup, /consultant-taste-practice[\s\S]*?consultant-taste-kicker">探索尝试<\/div>[\s\S]*?consultant-taste-recommendation[\s\S]*?<h3>舌尖上的正念<\/h3>[\s\S]*?慢煮一壶绿豆汤、酸梅汤，或自制水果冰棒、冰冻葡萄，专注感受冰凉在口腔化开的清甜，用味觉的“微凉”抵消体感的燥热。/, '探索尝试应像推荐模块一样在独立柔白内容卡中呈现');
assert.match(html, /\.consultant-taste-card\{[^}]*background:rgba\(255,255,255,\.72\)[^}]*box-shadow:0 14px 34px rgba\(110,88,78,\.11\)/, '主动探索尝试应延续互动页的柔白卡片样式');
assert.match(html, /\.consultant-taste-signal,\.consultant-taste-practice p\{color:var\(--consultant-ink\);font-family:var\(--sans\);font-size:13px;font-weight:400;line-height:1\.7\}/, '触发信号与探索说明应共用统一正文样式');
assert.match(html, /\.consultant-taste-recommendation\{margin-top:10px;padding:15px 14px 14px;border-radius:18px;background:rgba\(255,255,255,\.82\);box-shadow:0 9px 24px rgba\(110,88,78,\.10\)/, '舌尖上的正念应使用与推荐入口一致的柔白表面层');
assert.match(consultantPageMarkup, /class="consultant-user-bubble">我最近有点迷茫<\/div>/, '互动页应展示用户关于迷茫的新消息');
assert.doesNotMatch(consultantPageMarkup, /你不是没有方向|是两处生活同时在拉你/, '迷茫消息不应先替用户下总结标题');
assert.match(consultantPageMarkup, /class="consultant-agent-message consultant-clarity-message"[\s\S]*?<b class="consultant-section-label">声音线索<\/b>[\s\S]*?反复提到“换个环境”“看看新的机会”[\s\S]*?与对象的几段对话里[\s\S]*?争执和长时间停顿/, '声音线索一个模块内应同时呈现跳槽与伴侣争吵');
assert.match(consultantPageMarkup, /<b class="consultant-section-label">身体数据<\/b>[\s\S]*?HRV 连续低于个人基线[\s\S]*?压力高位/, '迷茫分析应补充 HRV 与压力状态的身体数据');
assert.match(consultantPageMarkup, /class="consultant-analysis-card consultant-clarity-card"[\s\S]*?class="consultant-evidence"[\s\S]*?class="consultant-evidence-item"[\s\S]*?声音线索[\s\S]*?class="consultant-evidence-item"[\s\S]*?身体数据[\s\S]*?class="consultant-hypothesis"[\s\S]*?consultant-hypothesis-label consultant-section-label">推测<\/div>\s*<p>工作去留和亲密关系同时需要你做判断，迷茫更像是选择力被多重压力占满了。<\/p>[\s\S]*?class="consultant-intervention-board"[\s\S]*?consultant-intervention-title consultant-section-label">推荐<\/div>/, '卡牌分析应复用压力分析的声音、身体、推测和推荐结构');
assert.doesNotMatch(consultantPageMarkup, /consultant-clarity-clues|consultant-clarity-clue|consultant-clarity-synthesis/, '卡牌分析不应继续使用造成标题与分割线混乱的独立结构');
assert.match(consultantPageMarkup, /class="consultant-card-draw-preview"[^>]*?onclick="openReflectionDeck\(\)"[\s\S]*?潜意识探索[\s\S]*?抽取卡牌，探索内心/, '迷茫解读应使用精简的潜意识探索入口文案');
assert.doesNotMatch(sleepMusicButtonMarkup + consultantPageMarkup.match(/<button class="consultant-card-draw-preview"[\s\S]*?<\/button>/)?.[0], /开始探索/, '卡牌入口不应再显示“开始探索”');
assert.match(consultantPageMarkup, /class="consultant-card-draw-mini"[^>]*><img src="\.\/抽卡\/背面\.png"/, '消息中的探索入口也应使用同一套真实卡背缩略图');
assert.match(consultantPageMarkup, /id="consultantReflectionModal"[^>]*role="dialog"[^>]*aria-modal="true"[^>]*aria-hidden="true"/, '抽卡体验应在可访问的弹窗中完成');
assert.match(consultantPageMarkup, /LOOOVE · 潜意识探索/, '弹窗品牌栏应统一使用“潜意识探索”');
assert.doesNotMatch(consultantPageMarkup, /不寻找正确答案|先让一张图，替你打开一个入口。/, '抽卡首屏应去掉多余引导标题');
assert.match(consultantPageMarkup, /data-reflection-stage="deck"[\s\S]*?凭第一感觉抽取 3 张。[\s\S]*?src="\.\/抽卡\/背面\.png"[\s\S]*?onclick="drawReflectionCard\(\)"[\s\S]*?抽 3 张/, '弹窗第一步应使用本地卡背并允许用户一次抽取三张');
assert.match(html, /\.consultant-reflection-instruction\{[^}]*font-size:19px/, '“凭第一感觉抽取 3 张”应放大为首屏视觉重点');
assert.match(consultantPageMarkup, /data-reflection-stage="reflect"[\s\S]*?src="\.\/抽卡\/28\.png"[\s\S]*?src="\.\/抽卡\/31\.png"[\s\S]*?src="\.\/抽卡\/36\.png"/, '翻牌后应展示抽卡目录中的三张真实卡牌');
assert.match(consultantPageMarkup, /id="reflectionAttraction"[\s\S]*?三张图里，哪一张最吸引你？[\s\S]*?id="reflectionAssociation"[\s\S]*?它让你想到了最近发生的什么？[\s\S]*?id="reflectionDirection"[\s\S]*?如果三张图连成一个故事，故事正在走向哪里？/, '翻牌后应提供三个不预设答案的联想问题');
const reflectionStageMarkup = (consultantPageMarkup.match(/data-reflection-stage="reflect"([\s\S]*?)<\/form>/) || [])[1] || '';
assert.doesNotMatch(reflectionStageMarkup, /placeholder=/, '三个卡牌输入框不应提供示例或提示内容干扰联想');
assert.match(consultantPageMarkup, /onclick="submitReflectionCard\(\)"[\s\S]*?完成并发送给 LOOOVE/, '用户应能完成抽卡并把内容发送给 LOOOVE');
assert.match(html, /\.consultant-reflection-form \.consultant-reflection-primary\{display:block;margin:10px auto 0\}/, '完成按钮应在表单中水平居中');
assert.match(html, /\.consultant-reflection-modal\.on\{opacity:1;visibility:visible;pointer-events:auto\}/, '抽卡弹窗开启时应具有明确的可见与交互状态');
assert.match(html, /@keyframes consultantCardReveal\{[^}]*transform:rotateY\(90deg\)[^}]*\}/, '抽卡应提供克制的翻牌揭示动效');
assert.match(html, /function openReflectionDeck\(\)/, '应提供打开抽卡弹窗的函数');
assert.match(html, /function drawReflectionCard\(\)/, '应提供揭示联想卡的函数');
assert.match(html, /function submitReflectionCard\(\)[\s\S]*?soundSignals[\s\S]*?attraction[\s\S]*?association[\s\S]*?direction[\s\S]*?lastLoooveReflectionPayload/, '提交时应把声音线索、三张卡片与三段回答整合成完整数据');
assert.match(html, /function appendReflectionInterpretation\(payload\)[\s\S]*?consultant-reflection-result[\s\S]*?LOOOVE 的解读/, '提交后应把 LOOOVE 的个性化解读追加回对话流');
assert.match(html, /\.consultant-reflection-result-card p,\.consultant-reflection-result-card footer\{[^}]*color:var\(--consultant-ink\)[^}]*font-family:var\(--serif\)[^}]*font-size:13px[^}]*line-height:1\.78/, '解读的两段正文应使用完全一致的字色、字体、字号和行距');
assert.match(html, /\.consultant-reflection-result-card footer\{[^}]*padding-top:0[^}]*border-top:0/, '解读下方正文不应再使用弱化的小字分隔样式');
assert.match(html, /function stripReflectionTerminalPunctuation\(text\)[\s\S]*?replace\(\/\[。！？!\?\]\+\$\//, '引用用户回答前应去掉末尾重复标点');
assert.match(html, /const quotedDirection=stripReflectionTerminalPunctuation\(payload\.direction\)/, 'AI 解读应使用已归一化标点的第三段回答');
assert.match(html, /id="consultantAgentInput"[^>]*placeholder="来和LOOOVE分享此刻的心事吧~"/, '互动页输入框应使用更轻松的分享提示');
assert.match(html, /function sendConsultantMessage\(\)/, '互动页应支持发送新的文字消息');
assert.match(html, /\.consultant-evidence-item span,\.consultant-hypothesis p,\.consultant-report-insight,\.consultant-proactive-copy,\.consultant-mantra-card footer,\.consultant-inline-agent\{[^}]*font-family:var\(--sans\)[^}]*font-size:13px[^}]*font-weight:400[^}]*line-height:1\.7/, '主动发送后的 LOOOVE 回复应与声音、身体数据正文使用同一字体规范');
assert.match(html, /id="consultantVoiceBtn"[^>]*onclick="consultantVoiceInput\(\)"[^>]*aria-label="语音输入"/, '互动页麦克风应明确作为 App 内语音输入入口');
assert.match(html, /function consultantVoiceInput\(\)[\s\S]*?input\.placeholder='正在听你说…'[\s\S]*?input\.value='我最近有点累，也有点说不上来的烦。'[\s\S]*?input\.focus\(\)/, 'App 语音输入结束后应把识别文字放回输入框供用户确认');
const consultantVoiceInputFunction = html.match(/function consultantVoiceInput\(\)\{[\s\S]*?\n\}/)?.[0] || '';
assert.doesNotMatch(consultantVoiceInputFunction, /戒指|声音片段|consultantPostAgentNotice|今天的新基线/, 'App 语音输入不应读取或分析戒指录音');
assert.doesNotMatch(html, /function launchConsultantIntervention\(type,btn\)/, '心法卡不需要保留旧的任务干预函数');
assert.match(html, /\.consultant-agent-composer\{[^}]*position:absolute[^}]*bottom:0/, '互动页输入区应固定在页面底部');
assert.doesNotMatch(consultantPageMarkup, /LOOOVE 解读用于自我觉察与日常支持，不替代专业医疗或心理诊断|若困扰持续或影响安全，请及时联系专业支持/, 'Demo 的互动页不应展示免责声明');
assert.match(html, /function openHomeAwarenessPlaceholder\(\)/, '新页面打开函数应存在');
assert.match(html, /function closeHomeAwarenessPlaceholder\(\)/, '新页面返回函数应存在');
assert.doesNotMatch(html, /try\{selectHomeFlow\('awareness'\);\}catch\(e\)\{\}/, '打开页面不应再自动弹出觉察详情');
assert.match(html, /id="homeBodyState"/, '身体状态跳转页应保留');
assert.match(html, /--soft-page-bg:\s*radial-gradient\(circle at 86% 16%,rgba\(238,188,174,\.12\),transparent 34%\),\s*radial-gradient\(circle at 16% 72%,rgba\(183,207,195,\.09\),transparent 36%\),\s*radial-gradient\(circle at 28% 10%,rgba\(226,205,171,\.08\),transparent 30%\),\s*linear-gradient\(160deg,#fff,#fffdfb 58%,#fffaf7\)/, '应定义柔白微渐变统一页面背景');
assert.match(html, /\.home-state-screen,#t-diary,#t-space\{background:var\(--soft-page-bg\)\}/, '身体状态、轨迹和我的页面应共用统一背景');
assert.match(html, /\.app-bg\{[^}]*background:var\(--soft-page-bg\)/, '页面切换时露出的应用底层也应使用统一柔白背景');
assert.match(html, /\.app-bg::after\{display:none\}/, '旧版深色底层叠色应停用');
assert.match(html, /@keyframes pageEnterStable\{from\{transform:translateY\(10px\)\}to\{transform:translateY\(0\)\}\}/, '切页动效应只轻微位移，不应从透明状态淡入');
assert.match(html, /\.tabpage\.on\{display:flex;animation:pageEnterStable/, '底部 Tab 切换首帧应保持不透明');
assert.match(html, /\.home-state-screen\.on\{display:block;animation:pageEnterStable/, '身体状态子页面切换首帧应保持不透明');
assert.match(html, /\.home-deep-screen\.on,\.home-child-screen\.on\{display:block;animation:pageEnterStable/, '首页其他子页面切换首帧应保持不透明');
assert.match(html, /\.app:not\(\.home-visual\)::before\{opacity:0;transition:none\}/, '离开首页时应立即隐藏图片层，避免切页残影');
assert.match(html, /\.app:not\(\.home-visual\) \.app-bg\{opacity:1;transition:none\}/, '离开首页时统一柔白底层应立即显示');
const softPageBackground = (html.match(/--soft-page-bg:([^;]+);/) || [])[1] || '';
assert.doesNotMatch(softPageBackground, /url\(/, '统一子页面背景不应使用图片');
assert.match(html, /id="homeBodyState"[\s\S]*?class="hsc-status">渐入平衡<\/div>[\s\S]*?class="hsc-sub">Loooveness 56<\/div>/, '身体状态页的状态词和分值应与首页一致');
const bodyStateMarkup = (html.match(/<div class="home-state-screen" id="homeBodyState">([\s\S]*?)(?=<div class="home-(?:deep|child)-screen")/) || [])[1] || '';
assert.doesNotMatch(bodyStateMarkup, /深度探索|body-ai-coach|实时解读/, '身体状态页应移除深度探索和 AI 实时解读');
assert.doesNotMatch(html, /id="homeDeepExplore"/, '深度探索空白页面应移除');
assert.match(html, /\.body-sleep-report \.ai-report-card\{min-height:156px;padding:26px 20px 24px\}/, '睡眠报告卡高度和内边距应增大');
assert.match(bodyStateMarkup, /class="body-sleep-insight"[\s\S]*?class="body-sleep-insight-label">LOOOVE 解读<\/div>[\s\S]*?昨夜 02:56 才入睡，是深睡比例偏低的主要原因——深夜入睡时生长激素分泌减少，深睡窗口收窄。睡眠效率 94% 表现不错，血氧全程稳定在安全区间。试着把入睡时间前移到 23:00 前，深睡眠会更充足。/, '睡眠报告概览卡应直接展示详情页的 LOOOVE 解读');
assert.match(html, /id="ov-sleep-report"[\s\S]*?class="sr-ai-lbl">LOOOVE 解读<\/div>/, '睡眠报告详情页也应使用 LOOOVE 解读命名');
assert.match(html, /\.body-sleep-insight\{margin-top:22px;padding-top:18px;border-top:1px solid rgba\(95,95,95,\.10\)\}/, '睡眠 AI 解读应以轻分隔线承接数据区');
assert.match(html, /\.body-sleep-insight-text\{margin-top:8px;font-family:var\(--sans\);font-size:12\.5px;line-height:1\.8;color:var\(--text-secondary\)\}/, '睡眠 AI 解读正文应沿用页面克制的正文样式');
assert.match(html, /id="ov-body-awareness"/, '身心觉察详情页应保留');

const trajectoryMarkup = (html.match(/<div class="tabpage" id="t-diary">([\s\S]*?)<\/div>\s*\n\s*<!-- ===== TAB 3/) || [])[1] || '';
const activeTrajectoryMarkup = trajectoryMarkup.replace(/<!--[\s\S]*?-->/g, '');
const trajectoryTabs = [...activeTrajectoryMarkup.matchAll(/<button class="growth-tab(?: on)?" data-growth="([^"]+)"[^>]*>([^<]+)<\/button>/g)]
  .map(([, value, label]) => ({ value, label: label.trim() }));
assert.deepEqual(trajectoryTabs, [
  { value: 'all', label: '全部' },
  { value: 'highlight', label: '高光' },
  { value: 'low', label: '波动' },
  { value: 'interaction', label: '互动' },
  { value: 'report', label: '报告' },
], '轨迹页应按“全部 / 高光 / 波动 / 互动 / 报告”的顺序展示分类');
assert.match(trajectoryMarkup, /<h2 class="serif">轨迹<\/h2>/, '轨迹页标题应精简为“轨迹”');
const trajectoryCardTypes = [...activeTrajectoryMarkup.matchAll(/class="growth-card [^"]+" data-growth="([^"]+)"/g)].map(([, type]) => type);
assert.ok(trajectoryCardTypes.length > 0, '轨迹页应保留成长记录');
assert.ok(trajectoryCardTypes.every(type => ['interaction', 'highlight', 'low', 'report'].includes(type)), '所有轨迹记录都应归入高光、低谷、互动或报告分类');
assert.deepEqual([...new Set(trajectoryCardTypes)].sort(), ['highlight', 'interaction', 'low', 'report'], '高光、低谷、互动和报告都应有可筛选的记录');
assert.match(html, /\.growth-day\.hide\{display:none\}/, '筛选后没有对应记录的日期标题应隐藏');
assert.doesNotMatch(activeTrajectoryMarkup, /class="growth-curve"/, '轨迹页不应继续渲染波浪曲线');
assert.match(html, /\.growth-line::before\{content:'';position:absolute;left:18px;top:12px;bottom:8px;width:1px;background:rgba\(238,132,102,\.34\);[^}]*z-index:1\}/, '轨迹时间轴应恢复为穿过节点中心的轻柔笔直细线');
assert.match(html, /function filterGrowthTrail\(btn\)[\s\S]*?querySelectorAll\('\.growth-day'\)[\s\S]*?classList\.toggle\('hide',!hasVisibleCard\)/, '轨迹筛选应同步清理没有可见记录的日期标题');
const highlightAndLowCards = [...activeTrajectoryMarkup.matchAll(/<article class="growth-card [^"]+" data-growth="(highlight|low)"[\s\S]*?<\/article>/g)].map(match => match[0]);
assert.ok(highlightAndLowCards.length >= 4, '高光与低谷应各提供工作与生活场景记录');
highlightAndLowCards.forEach(card => {
  assert.match(card, /class="growth-signal-preview"[\s\S]*?>声音<[\s\S]*?>身体</, '高光和低谷列表卡应同时展示声音与身体摘要');
  assert.match(card, /class="growth-summary-line"/, '高光和低谷列表卡应提供一句话总结');
});
const lifeHighlightCard = (activeTrajectoryMarkup.match(/<article class="growth-card [^"]+" data-growth="highlight" onclick="openGrowthRecord\('lifeHighlight'\)">([\s\S]*?)<\/article>/) || [])[1] || '';
assert.match(lifeHighlightCard, /和朋友散步时，你说了真话，也被温柔接住。[\s\S]*?笑声变多[\s\S]*?HRV 45ms · 压力 1\.9[\s\S]*?允许自己被关心/, '新增高光应记录朋友陪伴中的真实表达与身体放松');
assert.doesNotMatch(lifeHighlightCard, /工作|会议|评审|需求|方案/, '新增高光不应使用工作场景');
const lifeLowCard = (activeTrajectoryMarkup.match(/<article class="growth-card [^"]+" data-growth="low" onclick="openGrowthRecord\('lifeLow'\)">([\s\S]*?)<\/article>/) || [])[1] || '';
assert.match(lifeLowCard, /期待了一周的见面临时取消，你一个人回了家。[\s\S]*?连续说了三次“没关系”[\s\S]*?HRV 31ms · 压力 3\.8[\s\S]*?把自己的失落留在了身体里/, '新增低谷应记录生活约会取消后的失落与身体信号');
assert.doesNotMatch(lifeLowCard, /工作|会议|评审|需求|方案/, '新增低谷不应使用工作场景');
assert.match(activeTrajectoryMarkup, /data-growth="interaction"[\s\S]*?互动·抽卡/, '抽卡记录应统一命名为“互动·抽卡”');
assert.match(activeTrajectoryMarkup, /data-growth="interaction"[\s\S]*?互动·心法/, '心法记录应统一命名为“互动·心法”');
assert.match(activeTrajectoryMarkup, /data-growth="interaction"[\s\S]*?互动·绘画/, '绘画疗愈也应作为互动记录进入轨迹');
const cardTrajectoryCard = (activeTrajectoryMarkup.match(/<article class="growth-card [^"]+" data-growth="interaction" onclick="openGrowthRecord\('cardReflection'\)">([\s\S]*?)<\/article>/) || [])[1] || '';
assert.match(cardTrajectoryCard, /class="growth-interaction-media cards"[\s\S]*?src="\.\/抽卡\/28\.png"[\s\S]*?src="\.\/抽卡\/31\.png"[\s\S]*?src="\.\/抽卡\/36\.png"/, '抽卡列表卡应直接展示三张真实卡牌');
assert.match(cardTrajectoryCard, /class="growth-interaction-journey"[\s\S]*?<b>你<\/b><span>我最近有点迷茫[。]?<\/span>[\s\S]*?<b>结果<\/b><span>先看工作机会，关系等状态稳定后再谈<\/span>/, '抽卡列表应简要呈现用户起点与最终结果');
const drawingTrajectoryCard = (activeTrajectoryMarkup.match(/<article class="growth-card [^"]+" data-growth="interaction" onclick="openGrowthRecord\('drawingBreath'\)">([\s\S]*?)<\/article>/) || [])[1] || '';
assert.match(drawingTrajectoryCard, /互动·绘画[\s\S]*?src="\.\/呼吸画线\.jpg"[\s\S]*?<b>你<\/b><span>我有点烦躁[。]?<\/span>[\s\S]*?<b>结果<\/b><span>身体开始松开了[。]?<\/span>/, '绘画列表应展示完成作品以及调息前后的闭环');
const mantraTrajectoryCard = (activeTrajectoryMarkup.match(/<article class="growth-card [^"]+" data-growth="interaction" onclick="openGrowthRecord\('mantraMoment'\)">([\s\S]*?)<\/article>/) || [])[1] || '';
assert.match(mantraTrajectoryCard, /方案被反对，不等于能力被否定。[\s\S]*?class="growth-interaction-journey"[\s\S]*?<b>你<\/b><span>我最近压力好大[。]?<\/span>/, '心法列表应保留当时的表达');
assert.doesNotMatch(mantraTrajectoryCard, /<b>结果<\/b>|我气的是方案没有被认真讨论/, '心法没有用户产出，不应虚构结果或回应');
assert.doesNotMatch(mantraTrajectoryCard, /已收藏/, '心法记录无需显示收藏状态');
assert.match(activeTrajectoryMarkup, /data-growth="report"[\s\S]*?早间报告/, '报告分类应提供早间报告');
assert.match(activeTrajectoryMarkup, /data-growth="report"[\s\S]*?周报告/, '报告分类应提供周报告');
assert.match(activeTrajectoryMarkup, /data-growth="highlight"[\s\S]*?class="growth-kind kind-highlight">高光</, '高光记录应使用独立标签样式');
assert.match(activeTrajectoryMarkup, /data-growth="low"[\s\S]*?class="growth-kind kind-low">波动</, '波动记录应使用独立标签样式');
assert.doesNotMatch(html, /低谷/, '用户可见文案不应再使用“低谷”表达');
assert.equal((activeTrajectoryMarkup.match(/class="growth-kind kind-interaction">互动·(?:抽卡|心法|绘画)</g) || []).length, 3, '抽卡、心法与绘画应统一使用互动标签样式');
assert.equal((activeTrajectoryMarkup.match(/class="growth-kind kind-report">(?:早间|周)报告</g) || []).length, 2, '早间报告与周报告应统一使用报告标签样式');
assert.match(html, /\.growth-kind\.kind-highlight\{background:#fff0c7;color:#c67800;border-color:#ffd77d\}/, '高光标签应使用清亮蜜金色');
assert.match(html, /\.growth-kind\.kind-low\{background:#ffe8ed;color:#c64d66;border-color:#ffc0cc\}/, '低谷标签应使用清透莓果色');
assert.match(html, /\.growth-kind\.kind-interaction\{background:#ffe9df;color:#df6649;border-color:#ffc6b5\}/, '互动标签应使用珊瑚橙色');
assert.match(html, /\.growth-kind\.kind-report\{background:rgba\(255,255,255,\.74\);color:#c46d55;border-color:#efc0b0\}/, '报告标签应使用轻盈的暖色描边样式');
assert.doesNotMatch(html, /\.growth-kind\.kind-report\{[^}]*(?:#3f3632|#fffaf7)/, '报告标签不应继续使用过于突出的黑底白字');
assert.doesNotMatch(html, /\.growth-kind\.kind-report\{[^}]*(?:#f4eaff|#8d5bac|#dcc5ee)/, '报告标签不应残留紫色');
assert.doesNotMatch(html, /\.growth-kind\.kind-(?:interaction|report)\{[^}]*(?:#66826f|#667f96|rgba\(113,154,126|rgba\(112,143,170)/, '互动和报告标签不应残留蓝绿色');
assert.match(html, /const GROWTH_RECORDS=\{[\s\S]*?type:'signal'[\s\S]*?voiceDetail:[\s\S]*?bodyData:[\s\S]*?aiSummary:/, '高光和低谷详情数据应包含完整声音记录、身体数据与 AI 总结');
assert.match(html, /lifeHighlight:\{[\s\S]*?voiceDetail:'[^']*朋友[^']*'[\s\S]*?bodyData:\[\['45ms','HRV'\],\['68bpm','心率'\],\['1\.9','压力'\]\][\s\S]*?aiSummary:'[^']*被关心[^']*'/, '生活高光详情应包含朋友场景、身体数据与 AI 总结');
assert.match(html, /lifeLow:\{[\s\S]*?voiceDetail:'[^']*没关系[^']*'[\s\S]*?bodyData:\[\['31ms','HRV'\],\['79bpm','心率'\],\['3\.8','压力'\]\][\s\S]*?aiSummary:'[^']*失落[^']*'/, '生活低谷详情应包含约会取消、身体数据与 AI 总结');
assert.match(html, /type:'interaction'[\s\S]*?interactionKind:'绘画'[\s\S]*?type:'interaction'[\s\S]*?interactionKind:'抽卡'[\s\S]*?type:'interaction'[\s\S]*?interactionKind:'心法'/, '互动详情数据应分别支持绘画、抽卡与心法记录');
assert.match(html, /interactionKind:'绘画',title:'互动·绘画'[\s\S]*?interactionKind:'抽卡',title:'互动·抽卡'[\s\S]*?interactionKind:'心法',title:'互动·心法'/, '三类互动详情标题应使用统一命名');
assert.match(html, /type:'report'[\s\S]*?reportKind:'早间报告'[\s\S]*?type:'report'[\s\S]*?reportKind:'周报告'/, '报告详情数据应分别支持早间报告与周报告');
assert.match(html, /function growthSignalRecordMarkup\(record\)[\s\S]*?详细声音记录[\s\S]*?身体数据[\s\S]*?LOOOVE 总结/, '高光和波动详情页应展开三类完整信息，并使用 LOOOVE 总结命名');
assert.match(html, /drawingBreath:\{[\s\S]*?userMessage:'我有点烦躁。'[\s\S]*?loooveResponse:'[^']*绘画疗愈[^']*'[\s\S]*?toolThumb:'\.\/呼吸画线\.jpg'[\s\S]*?userReturn:''[\s\S]*?media:\['\.\/呼吸画线\.jpg'\][\s\S]*?aiSummary:'经过刚刚的疗愈，[^']*心率从 68 降至 64 bpm[^']*HRV 从 39 回升到 43 ms[^']*'/, '绘画互动详情应去掉完成句，保留作品，并使用“经过刚刚的疗愈”反馈身体变化');
assert.match(html, /cardReflection:\{[\s\S]*?userMessage:'我最近有点迷茫。'[\s\S]*?loooveResponse:'[^']*工作去留[^']*三张卡[^']*'[\s\S]*?toolThumb:'\.\/抽卡\/背面\.png'[\s\S]*?userReturn:'完成了三张卡和三个问题。'[\s\S]*?media:\['\.\/抽卡\/28\.png','\.\/抽卡\/31\.png','\.\/抽卡\/36\.png'\]/, '抽卡互动详情应保存前因、推荐缩略图、三张真实卡牌和用户完成结果');
assert.match(html, /mantraMoment:\{[\s\S]*?userMessage:'我最近压力好大。'[\s\S]*?loooveResponse:'[^']*会议争辩[^']*今日心法[^']*'[\s\S]*?aiSummary:'[^']*方案是否被采纳与个人能力分开[^']*'/, '心法互动详情应保留压力来源、心法推荐与 LOOOVE 总结');
const mantraRecord = (html.match(/mantraMoment:\{[\s\S]*?\n  \},/) || [''])[0];
assert.doesNotMatch(mantraRecord, /userReturn|returnLabel/, '心法没有用户产出，不应保存虚构的返回结果');
assert.match(html, /mantraMoment:\{[\s\S]*?recommendationTitle:'今日心法',recommendationText:'方案被反对，不等于能力被否定。'[\s\S]*?recommendationNote:\['带走有用的信息，允许自己有情绪；','等愤怒过去，再决定什么值得回应。'\]/, '轨迹详情的心法应与互动页保持相同的主句和两行说明层级');
const growthInteractionRenderer = (html.match(/function growthInteractionRecordMarkup\(record\)\{[\s\S]*?\n\}/) || [''])[0];
assert.match(growthInteractionRenderer, /const outputLabel=record\.interactionKind==='抽卡'\?'你的探索':record\.interactionKind==='绘画'\?'你的画作':'你的回应'/, '不同互动产出应使用贴合内容的亲近称谓');
assert.match(growthInteractionRenderer, /const hasOutput=Boolean\(record\.media\.length\|\|record\.items\.length\|\|record\.userReturn\)/, '只有真实存在产出时才应显示产出段落');
assert.match(growthInteractionRenderer, /growth-interaction-summary[\s\S]*?你说[\s\S]*?record\.userMessage[\s\S]*?outputRow[\s\S]*?LOOOVE 总结[\s\S]*?record\.aiSummary/, '轨迹互动详情应以亲近称谓汇总表达、真实产出和 LOOOVE 总结');
assert.doesNotMatch(growthInteractionRenderer, /用户表达|用户产出/, '轨迹详情不应使用疏离的“用户”称谓');
assert.doesNotMatch(growthInteractionRenderer, /growth-interaction-turn|record\.loooveResponse|recommendationTool/, '轨迹详情不应再次复刻完整聊天与推荐过程');
assert.match(html, /record\.media\.map\(\(src,index\)=>`<img src="\$\{esc\(src\)\}" alt="\$\{esc\(record\.interactionKind\)\}记录 \$\{index\+1\}">`\)/, '互动详情应按数据渲染绘画或卡牌图像');
assert.match(growthInteractionRenderer, /const outputCopy=!record\.media\.length&&!record\.items\.length&&record\.userReturn\?`<p class="growth-summary-copy">\$\{esc\(record\.userReturn\)\}<\/p>`:''/, '存在纯文字回应时应能作为真实产出展示');
assert.match(html, /\.growth-record-block\.growth-interaction-summary\{padding:0 16px\}/, '互动汇总应只使用一张外层卡片');
assert.match(html, /\.growth-summary-row\{padding:16px 0\}[\s\S]*?\.growth-summary-row\+\.growth-summary-row\{border-top:1px solid rgba\(95,95,95,\.10\)\}/, '三段汇总之间应只使用轻分隔线，不再嵌套聊天框');
assert.match(html, /\.growth-summary-label\{[^}]*color:var\(--primary\)[^}]*font-size:10px[^}]*font-weight:700/, '汇总段落标题应使用统一的橙色小标签');
assert.match(html, /\.growth-summary-copy\{[^}]*font-family:var\(--serif\)[^}]*font-size:14px[^}]*line-height:1\.85/, '你的表达、探索与 LOOOVE 总结应使用统一易读正文');
assert.match(html, /\.growth-ai-record\{padding:0;border-radius:0;background:transparent;box-shadow:none;font-family:var\(--serif\);font-size:14px;line-height:1\.85;color:var\(--text-primary\)\}/, '高光、波动与报告详情的 LOOOVE 总结都应去掉内部框层');
assert.match(html, /\.growth-card \.growth-interaction-media\.cards\{width:50%\}/, '抽卡列表图片组应缩小到当前尺寸的一半');
assert.match(html, /\.growth-card \.growth-interaction-media\.painting\{width:23%\}/, '绘画列表图片应从 46% 缩小到 23%');
assert.match(html, /\.growth-interaction-media\.cards\{grid-template-columns:repeat\(3,1fr\)/, '三张抽卡图片应并排展示');
assert.match(html, /\.growth-card-result-row\{display:flex;flex-direction:column;gap:8px;margin-top:12px\}/, '抽卡结果的三个白色块应纵向独立排列');
assert.match(html, /items:\[\s*\['三张图里，哪一张最吸引你？','远处的路。'\],\s*\['它让你想到了最近发生的什么？','我在认真考虑换工作，也在重新看待这段关系。'\],\s*\['如果三张图连成一个故事，故事正在走向哪里？','先走近新的机会，再决定哪些关系值得继续。'\]\s*\]/, '抽卡记录应保存三个问题及对应作答');
assert.match(html, /record\.items\.map\(\(\[question,answer\]\)=>`<div class="growth-card-result-item"><b>\$\{esc\(question\)\}<\/b><p>\$\{esc\(answer\)\}<\/p><\/div>`\)/, '抽卡详情应成对渲染问题与作答');
assert.match(html, /\.growth-card-result-item\{width:100%;[^}]*background:rgba\(255,255,255,\.78\)/, '每组抽卡问答应独立放在白色块中');
assert.match(html, /\.growth-card-result-item b\{display:block;[^}]*color:var\(--text-muted\)/, '抽卡问题应使用克制的辅助文字样式');
assert.match(html, /\.growth-card-result-item p\{margin-top:5px;[^}]*color:var\(--text-primary\)/, '抽卡作答应比问题更清晰突出');
assert.match(html, /function growthReportRecordMarkup\(record\)[\s\S]*?报告数据[\s\S]*?详细解读/, '报告详情页应比列表展示更多数据与解读');
assert.match(html, /const renderer=record\.type==='signal'\?growthSignalRecordMarkup:record\.type==='interaction'\?growthInteractionRecordMarkup:growthReportRecordMarkup/, '轨迹详情页应根据记录类型选择对应模板');
const activeFeatureMarkup = html.replace(/<!--[\s\S]*?-->/g, '');
assert.doesNotMatch(activeFeatureMarkup, /id="trajectoryBadgeWall"|class="growth-badge-float"|id="trajectoryReviewScreen"|class="growth-review-float"/, '勋章与 AI 洞察入口及页面应从当前 Demo 界面注释隐藏');
assert.match(html, /<!-- Demo 暂时隐藏：勋章[\s\S]*?id="trajectoryBadgeWall"[\s\S]*?-->/, '勋章页面代码应保留在注释中，方便后续恢复');
assert.match(html, /<!-- Demo 暂时隐藏：AI 洞察[\s\S]*?id="trajectoryReviewScreen"[\s\S]*?-->/, 'AI 洞察页面代码应保留在注释中，方便后续恢复');

const activeOrbitButtons = html
  .replace(/<!--[\s\S]*?-->/g, '')
  .match(/<button class="home-orbit-btn/g) || [];
assert.equal(activeOrbitButtons.length, 0, '首页旧入口按钮应全部注释');

const activeHtml = html.replace(/<!--[\s\S]*?-->/g, '');
assert.equal((activeHtml.match(/<div class="ai-report">/g) || []).length, 0, '首页旧 AI 身心教练毛玻璃内容应移除');

for (const [, script] of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)) {
  new Function(script);
}

console.log('home-awareness checks passed');
